name: apia
version: 1.0.0
synopsis: A Prize Is Assured is a personal work time logger
maintainer: 5-o
license: GPL-3

ghc-options: -Wall -O2

dependencies:
  - base >= 4.8.1.0 && < 5
  - directory
  - time
  - aeson >=0.10 && <1.0

library:
  source-dirs: src
  exposed-modules:
    - AnalyseHistory
    - ChooseAction
    - DecimalTime
    - ParseClockFile
    - TellUser

executables:
  apia:
    main: Main.hs
    source-dirs: app
    dependencies:
      - apia

tests:
  spec:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
